Create Cirrus_2020.2_GPU.md
hpc-uk/build-instructions pull request #52
Opened 2020-11-20 15:48 UTC by jsindt

Build instructions for GROMACS with GPUs

2020-11-20 16:19 UTC, aturner-epcc requested changes
Thanks @jsindt  looks like a typo in the cmake command. Can you check?

2020-11-20 16:19 UTC, aturner-epcc commented on GROMACS/Cirrus_2020.2_GPU.md
> +cmake ../ -DGMX_MPI=ON -DGMX_OPENMP=ON -DGMX_GPU=OFF -DGMX_X11=OFF \
This cake command seems to set GPU  off and on. Looks like a typo

2020-11-20 16:28 UTC, jsindt reviewed
Good spot -- I've fixed the typo.

2020-11-23 09:25 UTC, aturner-epcc approved these changes
Thanks for fixing

2020-11-23 09:25 UTC, merged